# Generated by Django 4.0 on 2024-11-19 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('abc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopost',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='ユーザー'),
        ),
    ]
